# Rebuilds sprites/*.jpg and imglist.js from tools/img_src/*.jpg (one photo per catalog key, e.g. 2018.jpg, 1858D.jpg, 5718BK.jpg).
# New photos: https://images.cutco.com/products/shop/h/<item number>.jpg  (e.g. 2018C.jpg), shrink to 320px, save under the catalog key.
from PIL import Image
import glob, os, json, math
os.chdir(os.path.dirname(os.path.abspath(__file__)) + '/..')
files=sorted(glob.glob('tools/img_src/*.jpg')); CELL=240; COLS=20; PER=180; pos={}; sheets=[]
for si in range(0,len(files),PER):
    batch=files[si:si+PER]; rows=math.ceil(len(batch)/COLS); sheet=Image.new('RGB',(COLS*CELL,rows*CELL),'white')
    for i,f in enumerate(batch):
        k=os.path.basename(f)[:-4]; im=Image.open(f).convert('RGB'); im.thumbnail((CELL-28,CELL-28))
        c,r=i%COLS,i//COLS; sheet.paste(im,(c*CELL+(CELL-im.width)//2, r*CELL+(CELL-im.height)//2)); pos[k]=[len(sheets),c,r]
    name=f'sprites/sheet{len(sheets)}.jpg'; sheet.save(name,'JPEG',quality=78,optimize=True,progressive=True); sheets.append(name)
open('imglist.js','w').write('/* GENERATED by tools/build_sprites.py: product photo sprite sheets (source photos in tools/img_src). */\nconst IMG_SPRITES = '+json.dumps({'cell':CELL,'cols':COLS,'sheets':sheets,'pos':pos},separators=(',',':'))+';\n')
print('sheets',len(sheets),'images',len(pos))
